apiVersion: v1
kind: Secret
metadata:
  name: config-vars
type: Opaque
stringData:
  CLUSTER_TOPOLOGY: "true"
  EXP_CLUSTER_RESOURCE_SET: "true"
  EXP_KUBEADM_BOOTSTRAP_FORMAT_IGNITION: "true"
  BOOTSTRAP_FORMAT_IGNITION: "true"
