apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: {{ include "capi-rke2-proxmox.cluster-name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "capi-rke2-proxmox.labels" . | nindent 4 }}
spec:
  clusterNetwork:
    apiServerPort: {{ .Values.cluster.clusterNetwork.apiServerPort }}
    serviceDomain: {{ .Values.cluster.clusterNetwork.serviceDomain }}
    pods:
      cidrBlocks:
        {{- toYaml .Values.cluster.clusterNetwork.pods.cidrBlocks | nindent 8 }}
    services:
      cidrBlocks:
        {{- toYaml .Values.cluster.clusterNetwork.services.cidrBlocks | nindent 8 }}
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: RKE2ControlPlane
    name: {{ include "capi-rke2-proxmox.cluster-name" . }}-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: ProxmoxCluster
    name: {{ include "capi-rke2-proxmox.cluster-name" . }}
