{{- $hash := include "ControlPlaneMachineTemplateHash" (dict "Global" .) }}
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: {{ include "capi-rke2-proxmox.cluster-name" . }}-control-plane-{{ $hash }}
  namespace: {{ .Release.Namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "capi-rke2-proxmox.cluster-name" . }}
    cluster.x-k8s.io/role: control-plane
spec:
  template:
    spec:
      {{- include "ControlPlaneMachineTemplateSpec" (dict "Global" .) | nindent 6 }}
