{{- range .Values.nodePools }}
{{- $hash := include "ProxmoxMachineTemplateHash" (dict "nodePool" . "Global" $) }}
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: {{ include "capi-rke2-proxmox.cluster-name" $ }}-{{ .name }}-proxmox-{{ $hash }}
  namespace: {{ $.Release.Namespace }}
  labels:
    cluster.x-k8s.io/cluster-name: {{ include "capi-rke2-proxmox.cluster-name" $ }}
    node-pool: {{ .name }}
spec:
  template:
    spec:
      {{- include "ProxmoxMachineTemplateSpec" (dict "nodePool" . "Global" $) | nindent 6 }}
{{- end }}
